package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"strings"
	"time"

	"golang.org/x/term"
)

// interactive returns true when stdin is a real terminal (not piped / subprocess).
func interactive() bool {
	return term.IsTerminal(int(os.Stdin.Fd()))
}

// waitForEnter pauses only in interactive (terminal) mode.
// When run as a subprocess (SSE server) or piped, it prints the label and continues.
func waitForEnter(label string) {
	if !interactive() {
		fmt.Printf("\n  ── %s\n", label)
		return
	}
	fmt.Printf("\n  ┌─ %s\n  └─ Press Enter to continue... ", label)
	bufio.NewReader(os.Stdin).ReadString('\n')
}

func main() {
	baseURL := flag.String("base-url", "https://api.iaexnetwork.com", "IAEX API base URL")
	region := flag.String("region", "in", "Region for developer register: in | eu")
	flag.Parse()
	*baseURL = strings.TrimRight(*baseURL, "/")

	// Keep console window open on Windows when run by double-click.
	// In non-interactive mode (piped / subprocess) this is skipped.
	if interactive() {
		defer func() {
			fmt.Print("\n  Press Enter to exit... ")
			bufio.NewReader(os.Stdin).ReadString('\n')
		}()
	}

	fmt.Println("╔══════════════════════════════════════════════════════════════╗")
	fmt.Println("║  IAEX Full Production Flow: 5 Independent Parties            ║")
	fmt.Println("║  Ed25519 Keys at Registration — All Setup Events Signed      ║")
	fmt.Println("╚══════════════════════════════════════════════════════════════╝")
	fmt.Printf("base-url : %s\n", *baseURL)
	fmt.Printf("region   : %s\n", *region)
	fmt.Println()
	fmt.Println("Each party (FarmFresh, RetailCo, TrustAudit, SwiftLogistics,")
	fmt.Println("NationalBank) operates as an independent developer application.")
	fmt.Println("All actors receive Ed25519 keypairs at registration. Org delegation,")
	fmt.Println("master creation, and master access grants are all actor-signed.")
	fmt.Println("Cross-party actor IDs are resolved via GET /actors/lookup.")

	defer func() {
		if r := recover(); r != nil {
			fmt.Printf("\n\n✗ SCENARIO FAILED: %v\n", r)
		}
	}()

	runID := fmt.Sprintf("%06d", time.Now().UnixMilli()%1000000)
	ns := &NetworkState{
		BaseURL: *baseURL,
		Region:  *region,
		RunID:   runID,
		Sup:     &SupParty{BaseURL: *baseURL, Region: *region},
		Buy:     &BuyParty{BaseURL: *baseURL, Region: *region},
		Aud:     &AudParty{BaseURL: *baseURL, Region: *region},
		Trn:     &TrnParty{BaseURL: *baseURL, Region: *region},
		Bnk:     &BnkParty{BaseURL: *baseURL, Region: *region},
	}

	// ── PHASE 1: Each party registers its actors + enrolls Ed25519 keys ──────
	waitForEnter("Phase 1: Independent Party Registration + Key Enrollment")
	fmt.Println("\n════ PHASE 1: REGISTRATION + KEY ENROLLMENT ═════════════════════")
	supRegister(ns)
	buyRegister(ns)
	audRegister(ns)
	trnRegister(ns)
	bnkRegister(ns)

	// ── PHASE 2: Each party onboards its org (creates FRL automatically) ─────
	waitForEnter("Phase 2: Onboarding (org + FRL creation)")
	fmt.Println("\n════ PHASE 2: ONBOARDING ════════════════════════════════════════")
	supOnboard(ns)
	buyOnboard(ns)
	audOnboard(ns)
	trnOnboard(ns)
	bnkOnboard(ns)

	// ── PHASE 3: Each party grants Zone B/C delegation to its own staff ──────
	// SUPPLIER_DELEGATION_GRANTED — actor-signed (org actor → own FRL ledger)
	waitForEnter("Phase 3: Org Delegation (Zone B/C — actor-signed)")
	fmt.Println("\n════ PHASE 3: ORG DELEGATION (Zone B/C) — SIGNED ════════════════")
	supDelegate(ns)
	buyDelegate(ns)
	audDelegate(ns)
	trnDelegate(ns)
	bnkDelegate(ns)

	// ── PHASE 4: Ledger + Masters ─────────────────────────────────────────────
	// ORDER_OPENED is authority-signed (server-side — ledger_id is generated by server).
	// TRACELEDGER_MASTER_CREATED — actor-signed (org actor → FRL/ORDER ledger).
	waitForEnter("Phase 4: Ledger + TraceLedgerMaster creation")
	fmt.Println("\n════ PHASE 4: LEDGER + MASTERS ══════════════════════════════════")
	tradeCreateOrderLedger(ns)
	supCreateFRLMaster(ns)
	buyCreateFRLMaster(ns)
	tradeCreateOrderMaster(ns)

	// ── PHASE 5: Zone E master access grants ──────────────────────────────────
	// MASTER_DELEGATION_GRANTED — actor-signed (org actor → parent ledger).
	waitForEnter("Phase 5: Master Access Grants (Zone E — actor-signed)")
	fmt.Println("\n════ PHASE 5: MASTER ACCESS GRANTS (Zone E) — SIGNED ══════════")
	supGrantFRLMasterAccess(ns)
	buyGrantFRLMasterAccess(ns)
	tradeGrantOrderMasterAccess(ns)

	// ── PHASE 6: Supplier FRL events — signed by FarmFresh staff ─────────────
	waitForEnter("Phase 6: Supplier FRL Events (FarmFresh — actor-signed)")
	fmt.Println("\n════ PHASE 6: SUPPLIER FRL EVENTS (FarmFresh — signed) ═════════")
	supFRLEvents(ns)

	// ── PHASE 7: ORDER ledger events — signed by SwiftLogistics/TrustAudit/NationalBank
	waitForEnter("Phase 7: ORDER Ledger Events (cross-party — actor-signed)")
	fmt.Println("\n════ PHASE 7: ORDER LEDGER EVENTS (signed) ══════════════════════")
	tradeOrderEvents(ns)

	// ── PHASE 8: Buyer FRL events — signed by RetailCo staff ─────────────────
	waitForEnter("Phase 8: Buyer FRL Events (RetailCo — actor-signed)")
	fmt.Println("\n════ PHASE 8: BUYER FRL EVENTS (RetailCo — signed) ═════════════")
	buyFRLEvents(ns)

	// ── PHASE 9: Close ────────────────────────────────────────────────────────
	waitForEnter("Phase 9: Close ORDER master + ledger")
	fmt.Println("\n════ PHASE 9: CLOSE ════════════════════════════════════════════")
	tradeClose(ns)

	// ── PHASE 10: Signature audit — fetches all events, shows sig per event ──
	waitForEnter("Phase 10: Signature Audit (non-repudiation proof)")
	fmt.Println("\n════ PHASE 10: SIGNATURE AUDIT ══════════════════════════════════")
	verifyWithSigAudit(ns)
}
